(package "lsp-smart-req"
         "0.1.0"
         "Require only the necessary modules")

(website-url "https://github.com/jcs-elpa/lsp-smart-req")
(keywords "internal" "lsp")

(package-file "lsp-smart-req.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "27.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
